In [1]:
# https://www.tensorflow.org/tutorials/quickstart/beginner
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [7]:
x_train.shape

(60000, 28, 28)

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()

In [6]:
predictions

array([[ 0.3744321 ,  0.17358969, -0.15066099, -0.73340255,  0.1960355 ,
         0.03739271, -0.02684559,  0.14301494,  0.07013736,  0.11122148]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.13775238, 0.11268714, 0.08148058, 0.04549594, 0.1152451 ,
        0.09833877, 0.09222028, 0.1092939 , 0.10161214, 0.10587373]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.319337

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2971 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1424 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1081 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0880 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0737 - accuracy: 0.9767


In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0726 - accuracy: 0.9776


[0.07259326428174973, 0.9775999784469604]

In [18]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [19]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8287187e-08, 3.5577269e-08, 6.1359935e-07, 3.0153278e-05,
        1.0617627e-10, 2.8848413e-08, 5.6153260e-14, 9.9996853e-01,
        7.8122824e-08, 5.4535377e-07],
       [1.0575013e-09, 1.4031373e-03, 9.9857581e-01, 1.0708735e-05,
        2.3206361e-13, 1.6449971e-09, 2.8717604e-08, 4.7747372e-11,
        1.0358881e-05, 7.4787133e-13],
       [1.1266518e-06, 9.9868494e-01, 1.5568701e-04, 8.3945724e-06,
        1.3308852e-05, 5.5803957e-07, 5.9958643e-06, 1.7630582e-04,
        9.5211598e-04, 1.6212620e-06],
       [9.9986184e-01, 9.8620834e-11, 2.6855920e-05, 4.2701953e-07,
        1.4453347e-07, 2.8619033e-06, 2.9199655e-05, 1.8591918e-06,
        4.4433082e-07, 7.6420081e-05],
       [5.1536445e-06, 1.7420350e-08, 2.6827518e-05, 2.9588580e-07,
        9.9353278e-01, 1.0415629e-06, 7.0820965e-07, 3.6199071e-05,
        1.4678091e-07, 6.3967933e-03]], dtype=float32)>